In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#to let colab have access to google drive for datasets
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#go to files by the leftside bar not at the top, locate your file as copy as path
path = '/content/drive/MyDrive/Colab Notebooks/CREDIT_CLASSIFICATION_1.csv'
df = pd.read_csv(path)

In [ ]:
print('Original Dataset')
print(df)

Original Dataset
            ID Customer_ID      Month             Name  Age Occupation  \
0       0x160a   CUS_0xd40  September    Aaron Maashoh   23  Scientist
1       0x160b   CUS_0xd40    October    Aaron Maashoh   24  Scientist
2       0x160c   CUS_0xd40   November    Aaron Maashoh   24  Scientist
3       0x160d   CUS_0xd40   December    Aaron Maashoh   24  Scientist
4       0x1616  CUS_0x21b1  September  Rick Rothackerj   28    Unknown
...        ...         ...        ...              ...  ...        ...
49995  0x25fe5  CUS_0x8600   December   Sarah McBridec   29  Architect
49996  0x25fee  CUS_0x942c  September            Nicks   25   Mechanic
49997  0x25fef  CUS_0x942c    October            Nicks   25   Mechanic
49998  0x25ff0  CUS_0x942c   November            Nicks   25   Mechanic
49999  0x25ff1  CUS_0x942c   December            Nicks   25   Mechanic

       Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
0           19114.12            1824.843333                  3
1           19114.12            1824.843333                  3
2           19114.12            1824.843333                  3
3           19114.12            1824.843333                  3
4           34847.84            3037.986667                  2
...              ...                    ...                ...
49995       20002.88            1929.906667                 10
49996       39628.99            3359.415833                  4
49997       39628.99            3359.415833                  4
49998       39628.99            3359.415833                  4
49999       39628.99            3359.415833                  4

       Num_Credit_Card  ...  Outstanding_Debt  Credit_Utilization_Ratio  \
0                    4  ...            809.98                 35.030402
1                    4  ...            809.98                 33.053114
2                    4  ...            809.98                 33.811894
3                    4  ...            809.98                 32.430559
4                    4  ...            605.03                 25.926822
...                ...  ...               ...                       ...
49995                8  ...           3571.70                 34.780553
49996                6  ...            502.38                 27.758522
49997                6  ...            502.38                 36.858542
49998                6  ...            502.38                 39.139840
49999                6  ...            502.38                 34.108530

      Payment_of_Min_Amount  Total_EMI_per_month  Amount_invested_monthly  \
0                        No            49.574949               236.642682
1                        No            49.574949                21.465380
2                        No            49.574949               148.233938
3                        No            49.574949                39.082511
4                        No            18.816215                39.684018
...                     ...                  ...                      ...
49995                   Yes            60.964772               146.486325
49996                    Nm            35.104023               181.442999
49997                    No            35.104023             10000.000000
49998                    No            35.104023                97.598580
49999                    No            35.104023               220.457878

                      Payment_Behaviour  Monthly_Balance  \
0        Low_spent_Small_value_payments       186.266702
1      High_spent_Medium_value_payments       361.444004
2       Low_spent_Medium_value_payments       264.675446
3      High_spent_Medium_value_payments       343.826873
4       High_spent_Large_value_payments       485.298434
...                                 ...              ...
49995    Low_spent_Small_value_payments       275.539570
49996    Low_spent_Small_value_payments       409.394562
49997    Low_spent_Large_value_payments       349.726332
49998   High_spent_Small_value_payments       463.238981
49999   Low_spent_Medium_value_payments       360.379683

      Credit_History_Age_Months  Num_Loan_Types_Derived          SSN
0                         273.0                       4  821-00-0265
1                         274.0                       4  821-00-0265
2                         225.0                       4  821-00-0265
3                         276.0                       4  821-00-0265
4                         327.0                       1  004-07-5839
...                         ...                     ...          ...
49995                     225.0                       5  031-35-0942
49996                     383.0                       2  078-73-5990
49997                     384.0                       2  078-73-5990
49998                     385.0                       2  078-73-5990
49999                     386.0                       2  078-73-5990

[50000 rows x 28 columns]

In [ ]:
df.head()

,ID,Customer_ID,Month,Name,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,...,Outstanding_Debt,Credit_Utilization_Ratio,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_History_Age_Months,Num_Loan_Types_Derived,SSN
0,0x160a,CUS_0xd40,September,Aaron Maashoh,23,Scientist,19114.12,1824.843333,3,4,...,809.98,35.030402,No,49.574949,236.642682,Low_spent_Small_value_payments,186.266702,273.0,4,821-00-0265
1,0x160b,CUS_0xd40,October,Aaron Maashoh,24,Scientist,19114.12,1824.843333,3,4,...,809.98,33.053114,No,49.574949,21.465380,High_spent_Medium_value_payments,361.444004,274.0,4,821-00-0265
2,0x160c,CUS_0xd40,November,Aaron Maashoh,24,Scientist,19114.12,1824.843333,3,4,...,809.98,33.811894,No,49.574949,148.233938,Low_spent_Medium_value_payments,264.675446,225.0,4,821-00-0265
3,0x160d,CUS_0xd40,December,Aaron Maashoh,24,Scientist,19114.12,1824.843333,3,4,...,809.98,32.430559,No,49.574949,39.082511,High_spent_Medium_value_payments,343.826873,276.0,4,821-00-0265
4,0x1616,CUS_0x21b1,September,Rick Rothackerj,28,Unknown,34847.84,3037.986667,2,4,...,605.03,25.926822,No,18.816215,39.684018,High_spent_Large_value_payments,485.298434,327.0,1,004-07-5839

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         50000 non-null  object
 1   Customer_ID                50000 non-null  object
 2   Month                      50000 non-null  object
 3   Name                       50000 non-null  object
 4   Age                        50000 non-null  int64
 5   Occupation                 50000 non-null  object
 6   Annual_Income              50000 non-null  float64
 7   Monthly_Inhand_Salary      50000 non-null  float64
 8   Num_Bank_Accounts          50000 non-null  int64
 9   Num_Credit_Card            50000 non-null  int64
 10  Interest_Rate              50000 non-null  int64
 11  Num_of_Loan                50000 non-null  int64
 12  Type_of_Loan               50000 non-null  object
 13  Delay_from_due_date        50000 non-null  int64
 14  Num_of_Delayed_Payment     50000 non-null  int64
 15  Changed_Credit_Limit       50000 non-null  float64
 16  Num_Credit_Inquiries       50000 non-null  int64
 17  Credit_Mix                 50000 non-null  object
 18  Outstanding_Debt           50000 non-null  float64
 19  Credit_Utilization_Ratio   50000 non-null  float64
 20  Payment_of_Min_Amount      50000 non-null  object
 21  Total_EMI_per_month        50000 non-null  float64
 22  Amount_invested_monthly    50000 non-null  float64
 23  Payment_Behaviour          50000 non-null  object
 24  Monthly_Balance            50000 non-null  float64
 25  Credit_History_Age_Months  50000 non-null  float64
 26  Num_Loan_Types_Derived     50000 non-null  int64
 27  SSN                        50000 non-null  object
dtypes: float64(9), int64(9), object(10)
memory usage: 10.7+ MB

1. Which occupations have the best credit profiles?

In [ ]:
# Define a mapping for Credit_Mix to numerical values
credit_mix_mapping = {
    'Good': 2,
    'Standard': 1,
    'Bad': 0,
    'Unknown': np.nan # Treat 'Unknown' as NaN for mean calculation
}

In [ ]:
# Apply the mapping to create a new numerical column
df['Credit_Mix_Score'] = df['Credit_Mix'].map(credit_mix_mapping)

# Group by 'Occupation' and calculate the mean of the new score
# Drop NaN values (from 'Unknown' credit mix) when calculating the mean
occupation_credit_profile = df.groupby('Occupation')['Credit_Mix_Score'].mean().sort_values(ascending=False)
print(occupation_credit_profile)

Occupation
Media_Manager    1.104538
Entrepreneur     1.096879
Lawyer           1.093198
Journalist       1.081974
Musician         1.081376
Architect        1.079816
Teacher          1.068438
Manager          1.067896
Unknown          1.067001
Accountant       1.063830
Scientist        1.061233
Engineer         1.048951
Developer        1.046548
Mechanic         1.045596
Writer           1.039915
Doctor           1.028026
Name: Credit_Mix_Score, dtype: float64

In [ ]:
print("Occupations with the best credit profiles based on Credit_Mix_Score (higher is better):")
display(occupation_credit_profile)

Occupations with the best credit profiles based on Credit_Mix_Score (higher is better):

Occupation
Media_Manager    1.104538
Entrepreneur     1.096879
Lawyer           1.093198
Journalist       1.081974
Musician         1.081376
Architect        1.079816
Teacher          1.068438
Manager          1.067896
Unknown          1.067001
Accountant       1.063830
Scientist        1.061233
Engineer         1.048951
Developer        1.046548
Mechanic         1.045596
Writer           1.039915
Doctor           1.028026
Name: Credit_Mix_Score, dtype: float64

How does age group affect borrowing behavior?

In [ ]:
# Create age groups from continuous age data
# age_bins=[0, 25, 35, 45, 55, 65, 75, 75+] defines the age ranges:["0-24", "25-34", "35-44", "45-54", "55-64", "65-74", "75+"]
#age_bins = [0, 25, 35, 45, 55, 65, 75, 100]
#age_labels = ["0-24", "25-34", "35-44", "45-54", "55-64", "65-74", "75+"]
#code By default, pd.cut is right=True, which means a bin of [0, 25] includes 25. Changing it to right=False makes the bin [0, 25),
#meaning it includes 0 up to 24.99, but excludes 25.
df['Age_Group'] = pd.cut(
                         df['Age'],
                         bins = [1, 25, 35, 45, 55, 65, 120],
                         labels = ["1-24", "25-34", "35-44", "45-54", "55-64", "65+"],
                         right=False
)

In [ ]:
# Borrowing behavior: average loan amount per age group
avg_loan_by_age = df.groupby("Age_Group")["Num_of_Loan"].mean()
customer_count = df.groupby("Age_Group")["Customer_ID"].nunique()
avg_credit_score = df.groupby("Age_Group")["Credit_Mix_Score"].mean()

/tmp/ipykernel_7629/1890202329.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_loan_by_age = df.groupby("Age_Group")["Num_of_Loan"].mean()
/tmp/ipykernel_7629/1890202329.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  customer_count = df.groupby("Age_Group")["Customer_ID"].nunique()
/tmp/ipykernel_7629/1890202329.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_credit_score = df.groupby("Age_Group")["Credit_Mix_Score"].mean()

In [ ]:
# Returns a single integer of unique customers
total_distinct_customers = df['Customer_ID'].nunique()

print(f"Total Unique Customers: {total_distinct_customers}")

Total Unique Customers: 12500

In [ ]:
#TO GET DISTINCT CUSTOMER COUNT BY AGE RANGE, RECALL THAT CUSTOMER_COUNT HAS BEEN DERIVED TO BE OF UNIQUE COUNTING WITH nunique()
print(customer_count)

Age_Group
1-24     3022
25-34    3710
35-44    3690
45-54    2051
55-64     325
65+         2
Name: Customer_ID, dtype: int64

In [ ]:
age_profile_summary = pd.DataFrame({
    'Average_Num_of_Loans': avg_loan_by_age,
    'Customer_Count': customer_count,
    'Average_Credit_Score': avg_credit_score
})
print("Age Group Profile:")
display(age_profile_summary)

Age Group Profile:

           Average_Num_of_Loans  Customer_Count  Average_Credit_Score
Age_Group
1-24                   8.059080            3022              0.902993
25-34                  7.894860            3710              1.006299
35-44                  7.385891            3690              1.016674
45-54                  6.180524            2051              1.428549
55-64                  7.030819             325              1.620795
65+                    3.500000               2              0.500000

Which income band carries the most debt?

In [ ]:
#qcut is a pandas function that divides data into quantile-based bins.q=4 means we want to split the income data into 4 equal-sized groups (quartiles).
#Each group will contain roughly 25% of the customers, based on their income distribution.
df['Income_Band'] = pd.qcut(
    df['Annual_Income'], q=4,
    labels=['low level income', 'mid level income', 'High level income', 'Very High Level Income']
)

In [ ]:
# Aggregate debt metrics by income band
annualincome_vs_debt =  df.groupby ('Income_Band')["Outstanding_Debt"].mean()
annualincome_vs_total_debt = df.groupby ('Income_Band')["Outstanding_Debt"] .sum()
customer_count= df.groupby ('Income_Band')["Customer_ID"].nunique()
monthlyincome_vs_debt = df.groupby ('Income_Band') ['Monthly_Inhand_Salary'].mean()

/tmp/ipykernel_7629/3530943651.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  annualincome_vs_debt =  df.groupby ('Income_Band')["Outstanding_Debt"].mean()
/tmp/ipykernel_7629/3530943651.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  annualincome_vs_total_debt = df.groupby ('Income_Band')["Outstanding_Debt"] .sum()
/tmp/ipykernel_7629/3530943651.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  customer_count= df.groupby ('Income_Band')["Customer_ID"].nunique()
/tmp/ipykernel_7629/3530943651.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  monthlyincome_vs_debt = df.groupby ('Income_Band') ['Monthly_Inhand_Salary'].mean()

In [ ]:
Debt_by_income_band = df.groupby("Income_Band").agg(
    avg_debt=("Outstanding_Debt", "mean"),
    total_debt=("Outstanding_Debt", "sum"),
    customer_count=("Customer_ID", "count"),
    avg_monthly_salary=("Monthly_Inhand_Salary", "mean")
)
Debt_by_income_band = Debt_by_income_band.round(2)
print(Debt_by_income_band)

                        avg_debt   total_debt  customer_count  \
Income_Band
low level income         1925.44  24067971.37           12500
mid level income         1260.88  15764732.62           12503
High level income        1564.26  19553279.27           12500
Very High Level Income    954.23  11925035.54           12497

                        avg_monthly_salary
Income_Band
low level income                   1178.75
mid level income                   2356.81
High level income                  4479.75
Very High Level Income             8709.26

/tmp/ipykernel_7629/1977778502.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  Debt_by_income_band = df.groupby("Income_Band").agg(

What credit mix predicts default risk?

In [ ]:
risk_profile = df.groupby("Credit_Mix").agg(
                   customer_count=("Customer_ID", "count"),
                   Avg_Delayed_Payments  = ('Num_of_Delayed_Payment', 'mean'),
                   Avg_Delay_Days        = ('Delay_from_due_date', 'mean'),
                   Avg_Outstanding_Debt  = ('Outstanding_Debt', 'mean'),
                   Avg_Num_Loans         = ('Num_of_Loan', 'mean')
                   )
risk_profile = risk_profile.round(2)
print(risk_profile)

            customer_count  Avg_Delayed_Payments  Avg_Delay_Days  \
Credit_Mix
Bad                   9556                 37.40           38.41
Good                 12260                 22.91           10.11
Standard             18379                 31.94           19.34
Unknown               9805                 27.69           21.15

            Avg_Outstanding_Debt  Avg_Num_Loans
Credit_Mix
Bad                      2992.78           9.92
Good                      742.05           6.80
Standard                 1062.21           7.21
Unknown                  1437.25           6.52

How does credit history length affect risk?

In [ ]:
#np.inf is NumPy’s representation of infinity. the last bin is [400, ∞), meaning any credit history age of 400 months or more will fall into the "400+ Mnths" category.
df['History_band'] = pd.cut(
    df['Credit_History_Age_Months'],
    bins=[0, 60, 120, 200, 400, np.inf],
    labels=['0–59 Mnths', '60–119 Mnths', '120–199 Mnths', '200-399 Mnths', '400+ Mnths'],
    right=False
)

In [ ]:
# Aggregate risk metrics by history band
history_length_risk = df.groupby("History_band").agg(
    avg_num_of_delayed_payment=("Num_of_Delayed_Payment", "mean"),              # proportion of customers who defaulted
    avg_credit_score=("Credit_Mix_Score", "mean"), # average credit score
    avg_debt=("Outstanding_Debt", "mean"),         # average debt
    customer_count=("Customer_ID", "count")        # number of customers
)
print(history_length_risk)

               avg_num_of_delayed_payment  avg_credit_score     avg_debt  \
History_band
0–59 Mnths                      29.727937          0.000000  3763.674171
60–119 Mnths                    41.558581          0.428305  2384.417678
120–199 Mnths                   33.993565          0.635247  1990.480172
200-399 Mnths                   26.499825          1.373966   947.582609
400+ Mnths                      26.787730          1.561934   755.220245

               customer_count
History_band
0–59 Mnths               1779
60–119 Mnths             6060
120–199 Mnths            9945
200-399 Mnths           31401
400+ Mnths                815

/tmp/ipykernel_7629/1726572256.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  history_length_risk = df.groupby("History_band").agg(

How does credit inquiries trend across months?

In [ ]:
inquiries_by_month = df.groupby("Month")["Num_Credit_Inquiries"].sum().sort_values(ascending=False)
print(" CREDIT INQUIRIES BY MONTH ")
print(inquiries_by_month)

 CREDIT INQUIRIES BY MONTH
Month
September    400250
November     392494
December     385215
October      305544
Name: Num_Credit_Inquiries, dtype: int64